# 使用官方的 Python 镜像作为基础镜像
FROM pypy:3.10-7.3.15-bookworm

# 设置工作目录
WORKDIR /app

# 将当前目录下的所有文件复制到工作目录
COPY . /app

# 安装依赖包
RUN apt update && apt-get install libzmq3-dev && \
    pip install --no-cache-dir -r requirements-reader.txt

# 暴露端口
EXPOSE 4242

# 启动服务
CMD ["python", "analog_rpc_server.py"]